### ISSUE TITLE
Consider customization of yaml features

### ISSUE THREAD

**Issue by Eijebong** [Eijebong/Archipelago-lobby#30]
Thought about this before and it just got asked if we could do something to have custom icons triggered on certain options, or if we could even outright ban uploads with said options.

I'm definitely onboard because of the second part.

We could have something like this:

```yaml
Pokemon Emerald:
  trainersanity:
    type: bool
    on: true
    icon: TrainerSanity
  dexsanity:
    type: bool
    on: true
    icon: DexSanity
WhateverGame:
  option:
    type: boolish
    on: trueish
    icon: WhateverIsImplementedInLobbyNoCustomImagesSorry
  option_banned:
    type: range
    on:
      greater_than: 75
    banned: true
```

Of course actual syntax, naming and matching features have to be defined.

This also requires #25
